import requests
import time
import os
from concurrent.futures import ThreadPoolExecutor, as_completed


# 代理
proxy = {'http': 'http://127.0.0.1:1083', 'https': 'http://127.0.0.1:1083'}

urls = [
    "https://kacey1--doyathing9.无效2023-05-18.co",
    "https://hucu1.yathingtodo.repl.co",
    "https://hucu2.yathingtodo.repl.co",
    "https://hucu3.yathingtodo.repl.co",
    "https://hucu4.yathingtodo.repl.co",
    "https://hucu5.yathingtodo.repl.co",
    "https://hucu6.yathingtodo.repl.co"
    "https://hucu7.yathingtodo.repl.co",
    "https://hucu8.yathingtodo.repl.co",
    "https://hucu9.yathingtodo.repl.co",
    "https://hucu10.yathingtodo.repl.co",
    "https://iuiu1.yagoodgoodya.repl.co",
    "https://iuiu2.yagoodgoodya.repl.co",
    "https://iuiu3.yagoodgoodya.repl.co",
    "https://iuiu4.yagoodgoodya.repl.co",
    "https://iuiu5.yagoodgoodya.repl.co",
    "https://iuiu6.yagoodgoodya.repl.co",
    "https://iuiu7.yagoodgoodya.repl.co",
    "https://iuiu8.yagoodgoodya.repl.co",
    "https://iuiu9.yagoodgoodya.repl.co",
    "https://iuiu10.yagoodgoodya.repl.co",
    "https://yuiu1.thingyado5.repl.co",
    "https://yuiu2.thingyado5.repl.co",
    "https://yuiu3.thingyado5.repl.co",
    "https://yuiu4.thingyado5.repl.co",
    "https://yuiu5.thingyado5.repl.co",
    "https://yuiu6.thingyado5.repl.co",
    "https://yuiu7.thingyado5.repl.co",
    "https://yuiu8.thingyado5.repl.co",
    "https://yuiu9.thingyado5.repl.co",
    "https://iuyu10.thingyado5.repl.co",
    "https://yuhj1.yugoodyu1.repl.co",
    "https://yuhj2.yugoodyu1.repl.co",
    "https://yuhj3.yugoodyu1.repl.co",
    "https://yuhj4.yugoodyu1.repl.co",
    "https://yuhj5.yugoodyu1.repl.co",
    "https://yuhj6.yugoodyu1.repl.co",
    "https://yuhj7.yugoodyu1.repl.co",
    "https://yuhj8.yugoodyu1.repl.co",
    "https://yuhj9.yugoodyu1.repl.co",
    "https://yuhj10.yugoodyu1.repl.co",
    "https://juyu1.yagood3.repl.co",
    "https://juyu2.yagood3.repl.co",
    "https://juyu3.yagood3.repl.co",
    "https://juyu4.yagood3.repl.co",
    "https://juyu5.yagood3.repl.co",
    "https://juyu6.yagood3.repl.co",
    "https://juyu7.yagood3.repl.co",
    "https://juyu8.yagood3.repl.co",
    "https://juyu9.yagood3.repl.co",
    "https://juyu10.yagood3.repl.co",
    "https://huyu1.yayagood2.repl.co",
    "https://huyu2.yayagood2.repl.co",
    "https://huyu3.yayagood2.repl.co",
    "https://huyu4.yayagood2.repl.co",
    "https://huyu5.yayagood2.repl.co",
    "https://huyu6.yayagood2.repl.co",
    "https://huyu7.yayagood2.repl.co",
    "https://huyu8.yayagood2.repl.co",
    "https://huyu9.yayagood2.repl.co",
    "https://huyu10.yayagood2.repl.co",
    "https://tytu1.1530054290.repl.co",
    "https://tytu2.1530054290.repl.co",
    "https://tytu3.1530054290.repl.co",
    "https://tytu4.1530054290.repl.co",
    "https://tytu5.1530054290.repl.co",
    "https://tytu6.1530054290.repl.co",
    "https://tytu7.1530054290.repl.co",
    "https://tytu8.1530054290.repl.co",
    "https://tytu9.1530054290.repl.co",
    "https://tytu10.1530054290.repl.co",
    "https://tcyu1.15651618096.repl.co",
    "https://tcyu2.15651618096.repl.co",
    "https://tcyu3.15651618096.repl.co",
    "https://tcyu4.15651618096.repl.co",
    "https://tcyu5.15651618096.repl.co",
    "https://tcyu6.15651618096.repl.co",
    "https://tcyu7.15651618096.repl.co",
    "https://tcyu8.15651618096.repl.co",
    "https://tcyu9.15651618096.repl.co",
    "https://tcyu10.15651618096.repl.co",
    "https://kchu1.ladymamalade9.repl.co",
    "https://kchu2.ladymamalade9.repl.co",
    "https://kchu3.ladymamalade9.repl.co",
    "https://kchu4.ladymamalade9.repl.co",
    "https://kchu5.ladymamalade9.repl.co",
    "https:// kchu6.ladymamalade9.repl.co",
    "https://kchu7.ladymamalade9.repl.co",
    "https://kchu8.ladymamalade9.repl.co",
    "https://kchu9.ladymamalade9.repl.co",
    "https://kchu10.ladymamalade9.repl.co",
    "https://a1293a1.peekbeek.repl.co",
    "https://a1293a2.peekbeek.repl.co",
    "https://a1293a3.peekbeek.repl.co",
    "https://a1293a4.peekbeek.repl.co",
    "https://a1293a5.peekbeek.repl.co",
    "https://a1293a6.peekbeek.repl.co",
    "https://a1293a7.peekbeek.repl.co",
    "https://a1293a8.peekbeek.repl.co",
    "https://a1293a9.peekbeek.repl.co",
    "https://a1293a10.peekbeek.repl.co",
    "https://rgttta-1.rgttta.repl.co",
    "https://rgttta-2.rgttta.repl.co",
    "https://rgttta-3.rgttta.repl.co",
    "https://rgttta-4.rgttta.repl.co",
    "https://rgttta-5.rgttta.repl.co",
    "https://rgttta-6.rgttta.repl.co",
    "https://rgttta-7.rgttta.repl.co",
    "https://rgttta-8.rgttta.repl.co",
    "https://rgttta-9.rgttta.repl.co",
    "https://rgttta-10.rgttta.repl.co",
    "https://pizvjdeewlfzt-1.pizvjdeewlfzt.repl.co",
    "https://pizvjdeewlfzt-2.pizvjdeewlfzt.repl.co",
    "https://pizvjdeewlfzt-3.pizvjdeewlfzt.repl.co",
    "https://pizvjdeewlfzt-4.pizvjdeewlfzt.repl.co",
    "https://pizvjdeewlfzt-5.pizvjdeewlfzt.repl.co",
    "https://pizvjdeewlfzt-6.pizvjdeewlfzt.repl.co",
    "https://pizvjdeewlfzt-7.pizvjdeewlfzt.repl.co",
    "https://pizvjdeewlfzt-8.pizvjdeewlfzt.repl.co",
    "https://pizvjdeewlfzt-9.pizvjdeewlfzt.repl.co",
    "https://pizvjdeewlfzt-10.pizvjdeewlfzt.repl.co",
    "https://lzywgycaew-1.lzywgycaew.repl.co",
    "https://lzywgycaew-2.lzywgycaew.repl.co",
    "https://lzywgycaew-3.lzywgycaew.repl.co",
    "https://lzywgycaew-4.lzywgycaew.repl.co",
    "https://lzywgycaew-5.lzywgycaew.repl.co",
    "https://lzywgycaew-6.lzywgycaew.repl.co",
    "https://lzywgycaew-7.lzywgycaew.repl.co",
    "https://lzywgycaew-8.lzywgycaew.repl.co",
    "https://lzywgycaew-9.lzywgycaew.repl.co",
    "https://lzywgycaew-10.lzywgycaew.repl.co",
    "https://mfuvqyfavxlzawd-1.mfuvqyfavxlzawdrepl.co",
    "https://mfuvqyfavxlzawd-2.mfuvqyfavxlzawd.repl.co",
    "https://mfuvqyfavxlzawd-3.mfuvqyfavxlzawd.repl.co",
    "https://mfuvqyfavxlzawd-4.mfuvqyfavxlzawd.repl.co",
    "https://mfuvqyfavxlzawd-5.mfuvqyfavxlzawd.repl.co",
    "https://mfuvqyfavxlzawd-6.mfuvqyfavxlzawd.repl.co",
    "https://mfuvqyfavxlzawd-7.mfuvqyfavxlzawd.repl.co",
    "https://mfuvqyfavxlzawd-8.mfuvqyfavxlzawd.repl.co",
    "https://mfuvqyfavxlzawd-9.mfuvqyfavxlzawd.repl.co",
    "https://mfuvqyfavxlzawd-10.mfuvqyfavxlzawd.repl.co",
    "https://tygtuocnwfsszf-1.tygtuocnwfsszf.repl.co",
    "https://tygtuocnwfsszf-2.tygtuocnwfsszf.repl.co",
    "https://tygtuocnwfsszf-3.tygtuocnwfsszf.repl.co",
    "https://tygtuocnwfsszf-4.tygtuocnwfsszf.repl.co",
    "https://tygtuocnwfsszf-5.tygtuocnwfsszf.repl.co",
    "https://tygtuocnwfsszf-6.tygtuocnwfsszf.repl.co",
    "https://tygtuocnwfsszf-7.tygtuocnwfsszf.repl.co",
    "https://tygtuocnwfsszf-8.tygtuocnwfsszf.repl.co",
    "https://tygtuocnwfsszf-9.tygtuocnwfsszf.repl.co",
    "https://tygtuocnwfsszf-10.tygtuocnwfsszf.repl.co",
    "https://uegmuovbuwlryff-1.uegmuovbuwlryff.repl.co",
    "https://uegmuovbuwlryff-2.uegmuovbuwlryff.repl.co",
    "https://uegmuovbuwlryff-3.uegmuovbuwlryff.repl.co",
    "https://uegmuovbuwlryff-4.uegmuovbuwlryff.repl.co",
    "https://uegmuovbuwlryff-5.uegmuovbuwlryff.repl.co",
    "https://uegmuovbuwlryff-6.uegmuovbuwlryff.repl.co",
    "https://uegmuovbuwlryff-7.uegmuovbuwlryff.repl.co",
    "https://uegmuovbuwlryff-8.uegmuovbuwlryff.repl.co",
    "https://uegmuovbuwlryff-9.uegmuovbuwlryff.repl.co",
    "https://uegmuovbuwlryff-10.uegmuovbuwlryff.repl.co",
    "https://mbvcjq-1.mbvcjq.repl.co",
    "https://mbvcjq-2.mbvcjq.repl.co",
    "https://mbvcjq-3.mbvcjq.repl.co",
    "https://mbvcjq-4.mbvcjq.repl.co",
    "https://mbvcjq-5.mbvcjq.repl.co",
    "https://mbvcjq-6.mbvcjq.repl.co",
    "https://mbvcjq-7.mbvcjq.repl.co",
    "https://mbvcjq-8.mbvcjq.repl.co",
    "https://mbvcjq-9.mbvcjq.repl.co",
    "https://mbvcjq-10.mbvcjq.repl.co",
    "https://orbiicccgtzga-1.orbiicccgtzga.repl.co",
    "https://orbiicccgtzga-2.orbiicccgtzga.repl.co",
    "https://orbiicccgtzga-3.orbiicccgtzga.repl.co",
    "https://orbiicccgtzga-4.orbiicccgtzga.repl.co",
    "https://orbiicccgtzga-5.orbiicccgtzga.repl.co",
    "https://orbiicccgtzga-6.orbiicccgtzga.repl.co",
    "https://orbiicccgtzga-7.orbiicccgtzga.repl.co",
    "https://orbiicccgtzga-8.orbiicccgtzga.repl.co",
    "https://orbiicccgtzga-9.orbiicccgtzga.repl.co",
    "https://orbiicccgtzga-10.orbiicccgtzga.repl.co",
    "https://uuffmnvpu-1.uuffmnvpu.repl.co",
    "https://uuffmnvpu-2.uuffmnvpu.repl.co",
    "https://uuffmnvpu-3.uuffmnvpu.repl.co",
    "https://uuffmnvpu-4.uuffmnvpu.repl.co",
    "https://uuffmnvpu-5.uuffmnvpu.repl.co",
    "https://uuffmnvpu-6.uuffmnvpu.repl.co",
    "https://uuffmnvpu-7.uuffmnvpu.repl.co",
    "https://uuffmnvpu-8.uuffmnvpu.repl.co",
    "https://uuffmnvpu-9.uuffmnvpu.repl.co",
    "https://cvcmv-1.cvcmv.repl.co",
    "https://cvcmv-2.cvcmv.repl.co",
    "https://cvcmv-3.cvcmv.repl.co",
    "https://cvcmv-4.cvcmv.repl.co",
    "https://cvcmv-5.cvcmv.repl.co",
    "https://cvcmv-6.cvcmv.repl.co",
    "https://cvcmv-7.cvcmv.repl.co",
    "https://cvcmv-8.cvcmv.repl.co",
    "https://cvcmv-9.cvcmv.repl.co",
    "https://cvcmv-10.cvcmv.repl.co",
    "https://opqolhqmji-1.opqolhqmji.repl.co",
    "https://opqolhqmji-2.opqolhqmji.repl.co",
    "https://opqolhqmji-3.opqolhqmji.repl.co",
    "https://opqolhqmji-4.opqolhqmji.repl.co",
    "https://opqolhqmji-5.opqolhqmji.repl.co",
    "https://opqolhqmji-6.opqolhqmji.repl.co",
    "https://opqolhqmji-7.opqolhqmji.repl.co",
    "https://opqolhqmji-8.opqolhqmji.repl.co",
    "https://opqolhqmji-9.opqolhqmji.repl.co",
    "https://opqolhqmji-10.opqolhqmji.repl.co",
    "katie1.jujujus1.repl.co",
    "katie2.jujujus1.repl.co",
    "katie3.jujujus1.repl.co",
    "katie4.jujujus1.repl.co",
    "katie5.jujujus1.repl.co",
    "katie6.jujujus1.repl.co",
    "katie7.jujujus1.repl.co",
    "katie8.jujujus1.repl.co",
    "katie9.jujujus1.repl.co",
    "katie10.jujujus1.repl.co",
    "https://a1293a1.peekbeek.repl.co",
    "https://a1293a2.peekbeek.repl.co",
    "https://a1293a3.peekbeek.repl.co",
    "https://a1293a4.peekbeek.repl.co",
    "https://a1293a5.peekbeek.repl.co",
    "https://a1293a6.peekbeek.repl.co",
    "https://a1293a7.peekbeek.repl.co",
    "https://a1293a8.peekbeek.repl.co",
    "https://a1293a9.peekbeek.repl.co",
    "https://a1293a10.peekbeek.repl.co",
    "https://katie1.jujujus1.repl.co",
    "https://katie2.jujujus1.repl.co",
    "https://katie3.jujujus1.repl.co",
    "https://katie4.jujujus1.repl.co",
    "https://katie5.jujujus1.repl.co",
    "https://katie6.jujujus1.repl.co",
    "https://katie7.jujujus1.repl.co",
    "https://katie8.jujujus1.repl.co",
    "https://katie9.jujujus1.repl.co",
    "https://katie10.jujujus1.repl.co",
    "https://pkpk1.h4ghghg123.repl.co",
    "https://pkpk2.h4ghghg123.repl.co",
    "https://pkpk3.h4ghghg123.repl.co",
    "https://pkpk4.h4ghghg123.repl.co",
    "https://pkpk5.h4ghghg123.repl.co",
    "https://pkpk6.h4ghghg123.repl.co",
    "https://pkpk7.h4ghghg123.repl.co",
    "https://pkpk8.h4ghghg123.repl.co",
    "https://pkpk9.h4ghghg123.repl.co",
    "https://pkpk10.h4ghghg123.repl.co",
    "https://kuku1.pistolwayne.repl.co",
    "https://kuku2.pistolwayne.repl.co",
    "https://kuku3.pistolwayne.repl.co",
    "https://kuku4.pistolwayne.repl.co",
    "https://kuku5.pistolwayne.repl.co",
    "https://kuku6.pistolwayne.repl.co",
    "https://kuku7.pistolwayne.repl.co",
    "https://kuku8.pistolwayne.repl.co",
    "https://kuku9.pistolwayne.repl.co",
    "https://kuku10.pistolwayne.repl.co",
    "https://kgkg1.jujucchj.repl.co",
    "https://kgkg2.jujucchj.repl.co",
    "https://kgkg3.jujucchj.repl.co",
    "https://kgkg4.jujucchj.repl.co",
    "https://kgkg5.jujucchj.repl.co",
    "https://kgkg6.jujucchj.repl.co",
    "https://kgkg7.jujucchj.repl.co",
    "https://kgkg8.jujucchj.repl.co",
    "https://kgkg9.jujucchj.repl.co",
    "https://kgkg10.jujucchj.repl.co",
    "https://ujuj1.hjhj1234s.repl.co",
    "https://ujuj2.hjhj1234s.repl.co",
    "https://ujuj3.hjhj1234s.repl.co",
    "https://ujuj4.hjhj1234s.repl.co",
    "https://ujuj5.hjhj1234s.repl.co",
    "https://ujuj6.hjhj1234s.repl.co",
    "https://ujuj7.hjhj1234s.repl.co",
    "https://ujuj8.hjhj1234s.repl.co",
    "https://ujuj9.hjhj1234s.repl.co",
    "https://ujuj10.hjhj1234s.repl.co",
    "https://juou1.jkjk123jk.repl.co",
    "https://juou2.jkjk123jk.repl.co",
    "https://juou3.jkjk123jk.repl.co",
    "https://juou4.jkjk123jk.repl.co",
    "https://juou5.jkjk123jk.repl.co",
    "https://juou6.jkjk123jk.repl.co",
    "https://juou7.jkjk123jk.repl.co",
    "https://juou8.jkjk123jk.repl.co",
    "https://juou9.jkjk123jk.repl.co",
    "https://juou10.jkjk123jk.repl.co",







    "https://jxqqqgmzwnq-1.jxqqqgmzwnq.repl.co",
    "https://jxqqqgmzwnq-2.jxqqqgmzwnq.repl.co",
    "https://jxqqqgmzwnq-3.jxqqqgmzwnq.repl.co",
    "https://jxqqqgmzwnq-4.jxqqqgmzwnq.repl.co",
    "https://jxqqqgmzwnq-5.jxqqqgmzwnq.repl.co",
    "https://jxqqqgmzwnq-6.jxqqqgmzwnq.repl.co",
    "https://jxqqqgmzwnq-7.jxqqqgmzwnq.repl.co",
    "https://jxqqqgmzwnq-8.jxqqqgmzwnq.repl.co",
    "https://jxqqqgmzwnq-9.jxqqqgmzwnq.repl.co",
    "https://jxqqqgmzwnq-10.jxqqqgmzwnq.repl.co",
    "https://ewksowetovk-1.ewksowetovk.repl.co",
    "https://ewksowetovk-2.ewksowetovk.repl.co",
    "https://ewksowetovk-3.ewksowetovk.repl.co",
    "https://ewksowetovk-4.ewksowetovk.repl.co",
    "https://ewksowetovk-5.ewksowetovk.repl.co",
    "https://ewksowetovk-6.ewksowetovk.repl.co",
    "https://ewksowetovk-7.ewksowetovk.repl.co",
    "https://ewksowetovk-8.ewksowetovk.repl.co",
    "https://ewksowetovk-9.ewksowetovk.repl.co",
    "https://tmhhbwxehrysxrr-1.tmhhbwxehrysxrr.repl.co",
    "https://tmhhbwxehrysxrr-2.tmhhbwxehrysxrr.repl.co",
    "https://tmhhbwxehrysxrr-3.tmhhbwxehrysxrr.repl.co",
    "https://tmhhbwxehrysxrr-4.tmhhbwxehrysxrr.repl.co",
    "https://tmhhbwxehrysxrr-5.tmhhbwxehrysxrr.repl.co",
    "https://tmhhbwxehrysxrr-6.tmhhbwxehrysxrr.repl.co",
    "https://tmhhbwxehrysxrr-7.tmhhbwxehrysxrr.repl.co",
    "https://tmhhbwxehrysxrr-8.tmhhbwxehrysxrr.repl.co",
    "https://tmhhbwxehrysxrr-9.tmhhbwxehrysxrr.repl.co",
    "https://vkmgovqdjwd-1.vkmgovqdjwd.repl.co",
    "https://vkmgovqdjwd-2.vkmgovqdjwd.repl.co",
    "https://vkmgovqdjwd-3.vkmgovqdjwd.repl.co",
    "https://vkmgovqdjwd-4.vkmgovqdjwd.repl.co",
    "https://vkmgovqdjwd-5.vkmgovqdjwd.repl.co",
    "https://vkmgovqdjwd-6.vkmgovqdjwd.repl.co",
    "https://vkmgovqdjwd-7.vkmgovqdjwd.repl.co",
    "https://vkmgovqdjwd-8.vkmgovqdjwd.repl.co",
    "https://ysvrfopr-1.ysvrfopr.repl.co",
    "https://ysvrfopr-2.ysvrfopr.repl.co",
    "https://ysvrfopr-3.ysvrfopr.repl.co",
    "https://ysvrfopr-4.ysvrfopr.repl.co",
    "https://ysvrfopr-5.ysvrfopr.repl.co",
    "https://ysvrfopr-6.ysvrfopr.repl.co",
    "https://ysvrfopr-7.ysvrfopr.repl.co",
    "https://ysvrfopr-8.ysvrfopr.repl.co",
    "https://ysvrfopr-9.ysvrfopr.repl.co",
    "https://ysvrfopr-10.ysvrfopr.repl.co",
    "https://kiqdyfgunvjk-1.kiqdyfgunvjk.repl.co",
    "https://kiqdyfgunvjk-2.kiqdyfgunvjk.repl.co",
    "https://kiqdyfgunvjk-3.kiqdyfgunvjk.repl.co",
    "https://kiqdyfgunvjk-4.kiqdyfgunvjk.repl.co",
    "https://kiqdyfgunvjk-5.kiqdyfgunvjk.repl.co",
    "https://kiqdyfgunvjk-6.kiqdyfgunvjk.repl.co",
    "https://kiqdyfgunvjk-7.kiqdyfgunvjk.repl.co",
    "https://kiqdyfgunvjk-8.kiqdyfgunvjk.repl.co",
    "https://cegujxkke-1.cegujxkke.repl.co",
    "https://cegujxkke-2.cegujxkke.repl.co",
    "https://cegujxkke-3.cegujxkke.repl.co",
    "https://cegujxkke-4.cegujxkke.repl.co",
    "https://cegujxkke-5.cegujxkke.repl.co",
    "https://cegujxkke-6.cegujxkke.repl.co",
    "https://cegujxkke-7.cegujxkke.repl.co",
    "https://cegujxkke-8.cegujxkke.repl.co",
    "https://cegujxkke-9.cegujxkke.repl.co",
    "https://shjmidstth-1.shjmidstth.repl.co",
    "https://shjmidstth-2.shjmidstth.repl.co",
    "https://shjmidstth-3.shjmidstth.repl.co",
    "https://shjmidstth-4.shjmidstth.repl.co",
    "https://shjmidstth-5.shjmidstth.repl.co",
    "https://shjmidstth-6.shjmidstth.repl.co",
    "https://shjmidstth-7.shjmidstth.repl.co",
    "https://shjmidstth-8.shjmidstth.repl.co",
    "https://shjmidstth-9.shjmidstth.repl.co",
    "https://ouhnuzlw-1.ouhnuzlw.repl.co",
    "https://ouhnuzlw-2.ouhnuzlw.repl.co",
    "https://ouhnuzlw-3.ouhnuzlw.repl.co",
    "https://ouhnuzlw-4.ouhnuzlw.repl.co",
    "https://ouhnuzlw-5.ouhnuzlw.repl.co",
    "https://ouhnuzlw-6.ouhnuzlw.repl.co",
    "https://ouhnuzlw-7.ouhnuzlw.repl.co",
    "https://ouhnuzlw-8.ouhnuzlw.repl.co",
    "https://ouhnuzlw-9.ouhnuzlw.repl.co",
    "https://xwczvccpsbbivwq-1.xwczvccpsbbivwq.repl.co",
    "https://xwczvccpsbbivwq-2.xwczvccpsbbivwq.repl.co",
    "https://xwczvccpsbbivwq-3.xwczvccpsbbivwq.repl.co",
    "https://xwczvccpsbbivwq-4.xwczvccpsbbivwq.repl.co",
    "https://xwczvccpsbbivwq-5.xwczvccpsbbivwq.repl.co",
    "https://xwczvccpsbbivwq-6.xwczvccpsbbivwq.repl.co",
    "https://xwczvccpsbbivwq-7.xwczvccpsbbivwq.repl.co",
    "https://xwczvccpsbbivwq-8.xwczvccpsbbivwq.repl.co",
    "https://xwczvccpsbbivwq-9.xwczvccpsbbivwq.repl.co",
    "https://xwczvccpsbbivwq-10.xwczvccpsbbivwq.repl.co",
    "https://usplaowkhrucsby-1.usplaowkhrucsby.repl.co",
    "https://usplaowkhrucsby-2.usplaowkhrucsby.repl.co",
    "https://usplaowkhrucsby-3.usplaowkhrucsby.repl.co",
    "https://usplaowkhrucsby-4.usplaowkhrucsby.repl.co",
    "https://usplaowkhrucsby-5.usplaowkhrucsby.repl.co",
    "https://usplaowkhrucsby-6.usplaowkhrucsby.repl.co",
    "https://usplaowkhrucsby-7.usplaowkhrucsby.repl.co",
    "https://usplaowkhrucsby-8.usplaowkhrucsby.repl.co",
    "https://usplaowkhrucsby-9.usplaowkhrucsby.repl.co",
    "https://usplaowkhrucsby-10.usplaowkhrucsby.repl.co",
    "https://jjwohtsrnvzdu-1.jjwohtsrnvzdu.repl.co",
    "https://jjwohtsrnvzdu-2.jjwohtsrnvzdu.repl.co",
    "https://jjwohtsrnvzdu-3.jjwohtsrnvzdu.repl.co",
    "https://jjwohtsrnvzdu-4.jjwohtsrnvzdu.repl.co",
    "https://jjwohtsrnvzdu-5.jjwohtsrnvzdu.repl.co",
    "https://jjwohtsrnvzdu-6.jjwohtsrnvzdu.repl.co",
    "https://jjwohtsrnvzdu-7.jjwohtsrnvzdu.repl.co",
    "https://jjwohtsrnvzdu-8.jjwohtsrnvzdu.repl.co",
    "https://jjwohtsrnvzdu-9.jjwohtsrnvzdu.repl.co",
    "https://jjwohtsrnvzdu-10.jjwohtsrnvzdu.repl.co",
    "https://uezojestexbab-1.uezojestexbab.repl.co",
    "https://uezojestexbab-2.uezojestexbab.repl.co",
    "https://uezojestexbab-3.uezojestexbab.repl.co",
    "https://uezojestexbab-4.uezojestexbab.repl.co",
    "https://uezojestexbab-5.uezojestexbab.repl.co",
    "https://uezojestexbab-6.uezojestexbab.repl.co",
    "https://uezojestexbab-7.uezojestexbab.repl.co",
    "https://uezojestexbab-8.uezojestexbab.repl.co",
    "https://uezojestexbab-9.uezojestexbab.repl.co",
    "https://uezojestexbab-10.uezojestexbab.repl.co",
    "https://tdqyssm-1.tdqyssm.repl.co",
    "https://tdqyssm-2.tdqyssm.repl.co",
    "https://tdqyssm-3.tdqyssm.repl.co",
    "https://tdqyssm-4.tdqyssm.repl.co",
    "https://tdqyssm-5.tdqyssm.repl.co",
    "https://tdqyssm-6.tdqyssm.repl.co",
    "https://tdqyssm-7.tdqyssm.repl.co",
    "https://tdqyssm-8.tdqyssm.repl.co",
    "https://tdqyssm-9.tdqyssm.repl.co",
    "https://tdqyssm-10.tdqyssm.repl.co",
    "https://nkmabvqknvvttng-1.nkmabvqknvvttng.repl.co",
    "https://nkmabvqknvvttng-2.nkmabvqknvvttng.repl.co",
    "https://nkmabvqknvvttng-3.nkmabvqknvvttng.repl.co",
    "https://nkmabvqknvvttng-4.nkmabvqknvvttng.repl.co",
    "https://nkmabvqknvvttng-5.nkmabvqknvvttng.repl.co",
    "https://nkmabvqknvvttng-6.nkmabvqknvvttng.repl.co",
    "https://nkmabvqknvvttng-7.nkmabvqknvvttng.repl.co",
    "https://nkmabvqknvvttng-8.nkmabvqknvvttng.repl.co",
    "https://nkmabvqknvvttng-9.nkmabvqknvvttng.repl.co",
    "https://awdryltm-1.awdryltm.repl.co",
    "https://awdryltm-2.awdryltm.repl.co",
    "https://awdryltm-3.awdryltm.repl.co",
    "https://awdryltm-4.awdryltm.repl.co",
    "https://awdryltm-5.awdryltm.repl.co",
    "https://awdryltm-6.awdryltm.repl.co",
    "https://awdryltm-7.awdryltm.repl.co",
    "https://awdryltm-8.awdryltm.repl.co",
    "https://awdryltm-9.awdryltm.repl.co",
    "https://awdryltm-10.awdryltm.repl.co",
    "https://skryfszmkrelfng-1.skryfszmkrelfng.repl.co",
    "https://skryfszmkrelfng-2.skryfszmkrelfng.repl.co",
    "https://skryfszmkrelfng-3.skryfszmkrelfng.repl.co",
    "https://skryfszmkrelfng-4.skryfszmkrelfng.repl.co",
    "https://skryfszmkrelfng-5.skryfszmkrelfng.repl.co",
    "https://skryfszmkrelfng-6.skryfszmkrelfng.repl.co",
    "https://skryfszmkrelfng-7.skryfszmkrelfng.repl.co",
    "https://skryfszmkrelfng-8.skryfszmkrelfng.repl.co",
    "https://skryfszmkrelfng-9.skryfszmkrelfng.repl.co",
    "https://pfculvsinivpcqx-1.pfculvsinivpcqx.repl.co",
    "https://pfculvsinivpcqx-2.pfculvsinivpcqx.repl.co",
    "https://pfculvsinivpcqx-3.pfculvsinivpcqx.repl.co",
    "https://pfculvsinivpcqx-4.pfculvsinivpcqx.repl.co",
    "https://pfculvsinivpcqx-5.pfculvsinivpcqx.repl.co",
    "https://pfculvsinivpcqx-6.pfculvsinivpcqx.repl.co",
    "https://pfculvsinivpcqx-7.pfculvsinivpcqx.repl.co",
    "https://pfculvsinivpcqx-8.pfculvsinivpcqx.repl.co",
    "https://pfculvsinivpcqx-9.pfculvsinivpcqx.repl.co",
    "https://pfculvsinivpcqx-10.pfculvsinivpcqx.repl.co",
    "https://jkbjkymuls-1.jkbjkymuls.repl.co",
    "https://jkbjkymuls-2.jkbjkymuls.repl.co",
    "https://jkbjkymuls-3.jkbjkymuls.repl.co",
    "https://jkbjkymuls-4.jkbjkymuls.repl.co",
    "https://jkbjkymuls-5.jkbjkymuls.repl.co",
    "https://jkbjkymuls-6.jkbjkymuls.repl.co",
    "https://jkbjkymuls-7.jkbjkymuls.repl.co",
    "https://jkbjkymuls-8.jkbjkymuls.repl.co",
    "https://jkbjkymuls-9.jkbjkymuls.repl.co",
    "https://jkbjkymuls-10.jkbjkymuls.repl.co",
    "https://uvgmuzaomwrf-1.uvgmuzaomwrf.repl.co",
    "https://uvgmuzaomwrf-2.uvgmuzaomwrf.repl.co",
    "https://uvgmuzaomwrf-3.uvgmuzaomwrf.repl.co",
    "https://uvgmuzaomwrf-4.uvgmuzaomwrf.repl.co",
    "https://uvgmuzaomwrf-5.uvgmuzaomwrf.repl.co",
    "https://uvgmuzaomwrf-6.uvgmuzaomwrf.repl.co",
    "https://uvgmuzaomwrf-7.uvgmuzaomwrf.repl.co",
    "https://uvgmuzaomwrf-8.uvgmuzaomwrf.repl.co",
    "https://uvgmuzaomwrf-9.uvgmuzaomwrf.repl.co",
    "https://uvgmuzaomwrf-10.uvgmuzaomwrf.repl.co",
    "https://pxestnimeoka-1.pxestnimeoka.repl.co",
    "https://pxestnimeoka-2.pxestnimeoka.repl.co",
    "https://pxestnimeoka-3.pxestnimeoka.repl.co",
    "https://pxestnimeoka-4.pxestnimeoka.repl.co",
    "https://pxestnimeoka-5.pxestnimeoka.repl.co",
    "https://pxestnimeoka-6.pxestnimeoka.repl.co",
    "https://pxestnimeoka-7.pxestnimeoka.repl.co",
    "https://pxestnimeoka-8.pxestnimeoka.repl.co",
    "https://pxestnimeoka-9.pxestnimeoka.repl.co",
    "https://pxestnimeoka-10.pxestnimeoka.repl.co",
    "https://vqdvpmcsedzc-1.vqdvpmcsedzc.repl.co",
    "https://vqdvpmcsedzc-2.vqdvpmcsedzc.repl.co",
    "https://vqdvpmcsedzc-3.vqdvpmcsedzc.repl.co",
    "https://vqdvpmcsedzc-4.vqdvpmcsedzc.repl.co",
    "https://vqdvpmcsedzc-5.vqdvpmcsedzc.repl.co",
    "https://vqdvpmcsedzc-6.vqdvpmcsedzc.repl.co",
    "https://vqdvpmcsedzc-7.vqdvpmcsedzc.repl.co",
    "https://vqdvpmcsedzc-8.vqdvpmcsedzc.repl.co",
    "https://vqdvpmcsedzc-9.vqdvpmcsedzc.repl.co",
    "https://vqdvpmcsedzc-10.vqdvpmcsedzc.repl.co",
    "https://inddlhrg-1.inddlhrg.repl.co",
    "https://inddlhrg-2.inddlhrg.repl.co",
    "https://inddlhrg-3.inddlhrg.repl.co",
    "https://inddlhrg-4.inddlhrg.repl.co",
    "https://inddlhrg-5.inddlhrg.repl.co",
    "https://inddlhrg-6.inddlhrg.repl.co",
    "https://inddlhrg-7.inddlhrg.repl.co",
    "https://inddlhrg-8.inddlhrg.repl.co",
    "https://inddlhrg-9.inddlhrg.repl.co",
    "https://inddlhrg-10.inddlhrg.repl.co",

    
] 



while True:
    # 记录成功的链接
    successful_urls = []

    def request_url(url):
        retry = 0
        while True:
            try:
                new_url = f"{url}/vimeo.php?link=https://player.vimeo.com/video/211"
                response = requests.get(new_url, timeout=8)
                if response.status_code == 200 and 'gutierrez' in response.text:
                    print(f'{new_url} returned 200')
                    successful_urls.append(url)
                    return None  # 返回None表示成功
                else:
                    print(f'{new_url} returned {response.status_code}')
                    if retry < 2:
                        retry += 1
                        print(f'{new_url} retrying {retry}/2')
                    else:
                        break
            except requests.exceptions.RequestException as e:
                print(f'{new_url} failed: {e}')
                if retry < 2:
                    retry += 1
                    print(f'{new_url} retrying {retry}/2')
                else:
                    break
            time.sleep(1)  # 等待1秒后重试

    # 使用线程池并发请求
    with ThreadPoolExecutor(max_workers=20) as executor:
        futures = [executor.submit(request_url, url) for url in urls]
        # 等待所有请求完成
        for _ in as_completed(futures):
            pass

    # 将成功的链接写入文件
    if len(successful_urls) >= 140:
        with open('/mnt/d/常用/vimeo/传统方法刷-下载后再处理数据/urls.txt', 'w') as f:
            for url in successful_urls:
                f.write(url + '\n')
        print("以下链接未成功写入urls.txt:")
        print(set(urls) - set(successful_urls))
    else:
        print('Successful URLs less than 40, skipped writing to file.')

    # 如果所有链接都成功，则退出循环
    if set(successful_urls) == set(urls):
        print("All URLs succeeded!")
        break

    # 休眠一段时间后再次尝试
    print("一轮结束")
    print(len(successful_urls))
    time.sleep(4)
    os.system('clear')
